General improvements to mount scripts
E.g. use systemd, better input validation and error messages.

diff --git a/scripts/mount-iso b/scripts/mount-iso
--- a/scripts/mount-iso
+++ b/scripts/mount-iso
@@ -1,9 +1,18 @@
 #!/usr/bin/env bash
 
-if [[ ( -z "$1" ) || ( -z "$2" ) ]]; then
+iso="$1"
+dir="$2"
+
+if [[ -z "$iso" || -z "$dir" ]]; then
   echo "Usage:"
-  echo "iso-mount FILE.ISO /MOUNT/POINT"
-else
-  mount -o loop -t iso9660 "$1" "$2"
+  echo "mount-iso FILE.ISO /MOUNT/POINT"
+  exit 1
+elif [[ ! -f "$iso" ]]; then
+  echo "Error: \"$iso\" is not a file."
+  exit 1
+elif [[ ! -d "$dir" ]]; then
+  echo "Error: \"$dir\" is not a directory."
+  exit 1
 fi
 
+mount -o loop -t iso9660 "$iso" "$dir"
