Update pacman-disown

diff --git a/scripts/pacman-disown b/scripts/pacman-disown
--- a/scripts/pacman-disown
+++ b/scripts/pacman-disown
@@ -1,16 +1,48 @@
-#!/usr/bin/env bash
+#!/bin/bash
+# Utility to generate a list of all files that are not part of a package
+# Author: Spider.007 / Sjon
 
-tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
-db=$tmp/db
-fs=$tmp/fs
+TMPDIR=`mktemp -d`
+FILTER=$(sed '1,/^## FILTER/d' $0 | tr '\n' '|')
+FILTER=${FILTER%|}
 
-mkdir "$tmp"
-trap 'rm -rf "$tmp"' EXIT
+cd $TMPDIR
+find /bin /boot /etc /lib /opt /sbin /usr /var | sort -u > full
+pacman -Ql | tee owned_full | cut -d' ' -f2- | sed 's/\/$//' | sort -u > owned
 
-pacman -Qlq | sort -u > "$db"
+grep -Ev "^($FILTER)" owned > owned- && mv owned- owned
 
-find /bin /etc /lib /sbin /usr \
-  ! -name lost+found \
-  \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"
+echo -e '\033[1mOwned, but not found:\033[0m'
+comm -13 full owned | while read entry
+do
+        echo [`grep --max-count=1 $entry owned_full|cut -d' ' -f1`] $entry
+done | sort
 
-comm -23 "$fs" "$db"
+grep -Ev "^($FILTER)" full > full- && mv full- full
+
+echo -e '\n\033[1mFound, but not owned:\033[0m'
+comm -23 full owned
+
+rm $TMPDIR/{full,owned,owned_full} && rmdir $TMPDIR
+exit $?
+
+## FILTERED FILES / PATHS ##
+/boot/grub
+/dev
+/etc/X11/xdm/authdir
+/home
+/media
+/mnt
+/proc
+/root
+/srv
+/sys
+/tmp
+/var/abs
+/var/cache
+/var/games
+/var/log
+/var/lib/pacman
+/var/lib/mysql
+/var/run
+/var/tmp
