Clean up watch-files

diff --git a/scripts/watch-files b/scripts/watch-files
--- a/scripts/watch-files
+++ b/scripts/watch-files
@@ -1,13 +1,21 @@
 #!/usr/bin/env bash
 
 if [[ -d "$1" ]]; then
-  while inotifywait -qre close_write,moved_to,create "$1"; do
-    $2
-    sleep 1
-  done
+  path="$1"
+  opts="-r -e close_write,moved_to,create,delete"
 elif [[ -f "$1" ]]; then
-  while inotifywait -qe close_write,moved_to,create "$(dirname $1)"; do
-    $2
-    sleep 1
-  done
+  path="$(dirname "$1")"
+  opts="-e close_write"
+else
+  echo "Could not find file or directory \"$1\""
+  echo "Usage: watch-files PATH COMMAND [ARGS]"
+  exit 1
 fi
+
+shift 1
+
+while inotifywait -q $opts "$path" > /dev/null; do
+  $@
+  echo
+  sleep 1
+done
